# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: RunTestsOnPush

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
 

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Find solution
      shell: bash
      run: |
          SOLUTION=$(find . -maxdepth 3 -name "*.sln" | head -n 1)
          if [ -z "$SOLUTION" ]; then
            echo "No .sln file found"
            exit 1
          fi
          echo "SOLUTION=$SOLUTION" >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore "$SOLUTION"
    - name: Build
      run: dotnet build "$SOLUTION" --no-restore
    - name: Test
      run: dotnet test "$SOLUTION" --no-build --verbosity normal
